### ISSUE TITLE
Give me feedback!

### ISSUE THREAD

**Issue by jjb** [jjb/ruby-clock#1]
I just created https://github.com/jjb/ruby-clock!

Please tell me any and all questions or ideas!

**Comment by jjb** [comment]
ping @jmettraux

**Comment by jmettraux** [comment]
Hello,

I love the name.

Let me release rufus-scheduler 3.7.0 so that you don't have to tell people to point to rufus-scheduler's GitHub in their Gemfile.

**Comment by jjb** [comment]
> Let me release rufus-scheduler 3.7.0 so that you don't have to tell people to point to rufus-scheduler's GitHub in their Gemfile.

Great thanks, done now https://github.com/jjb/ruby-clock/commit/0bc899fca5b48205c0157f3017bb22ec498aba1f

**Comment by jmettraux** [comment]
Maybe `~> 3.7.0` is better than `>= 3.7.0`, else if there are breaking changes in rufus-scheduler 4.0.0, people will complain to me.

**Comment by jjb** [comment]
good idea, done
