### ISSUE TITLE
ruby-clock only starting up once SIGTERM is sent

### ISSUE THREAD

**Issue by danhunter** [jjb/ruby-clock#12]
Hi @jjb 

Trying to use ruby-clock for a clock process on Heroku. 

I've got the Procfile setup to execute the runner command, and can see the dyno boot up, but I don't get the `Starting ruby-clock with x jobs` message until I kill the dyno, at which point I get that log message immediately followed by `Shutting down ruby-clock 🐈️ 👋`

Ruby 2.5.3
Rails 6.1.4
ruby-clock 0.7.0

Appreciate any help!

**Comment by jjb** [comment]
@danhunter you may want to try v0.8.0.rc1, it has some nice improvements https://github.com/jjb/ruby-clock/blob/v0.8.0.rc1/CHANGELOG.md

**Comment by danhunter** [comment]
Appreciate the offer, but unfortunately not. It's all in their hands now.

**Comment by jjb** [comment]
@danhunter I just released 0.8.0.rc3 which no longer requires terrapin https://github.com/jjb/ruby-clock/pull/14
